## Gerardo Rodríguez Delgado 17110263 7M2
### Tarea 2: Tranformations & Quaternions

In [12]:
import numpy as np
from tarea1 import *

def grades_to_radians(deg):
    rad = (deg*np.pi)/180
    return rad

#### Variables

In [13]:
point = np.array([5, 5])
translated_point = np.array([1, 1])
deg_to_rotate = 90
scale_factor = 2

### Translation

In [14]:
def translate(point, new_point):
    assert (len(point) == 2), ' Original point is not a 2D point '
    assert (len(new_point) == 2), ' Translated point is not a 2D point '

    point = np.array([[1, 0, point[0]],[0, 1, point[1]]])
    new_point = euclidean2D_to_homogeneus(new_point)
    return point@new_point

In [15]:
translate(point, translated_point)

array([6, 6])

### Rotation

In [16]:
def rotate(point, deg):
    assert (len(point) == 2), ' Point is not a 2D point '
    angle = grades_to_radians(deg)
    rotation_matrix = np.array([[np.cos(angle),-np.sin(angle)],[np.sin(angle),np.cos(angle)]])
    return point@rotation_matrix

In [17]:
rotate(point, deg_to_rotate)


array([ 5., -5.])

### Rotation & Translation

In [18]:
def rotate_translate(point, new_point, deg):
    assert (len(point) == 2), ' Original Point is not a 2D point '
    assert (len(new_point) == 2), ' Translated point is not a 2D point '
    angle = grades_to_radians(deg)
    RT = np.array([[np.cos(angle),-np.sin(angle),new_point[0]],[np.sin(angle),np.cos(angle),new_point[1]]])
    point = euclidean2D_to_homogeneus(point)
    return RT@point

In [19]:
rotate_translate(point, translated_point, deg_to_rotate)

array([-4.,  6.])

### Rotation, translation & scalation

In [20]:
def rot_tra_scale(point, new_point, deg, scale_factor):
    assert (len(point) == 2), ' Original Point is not a 2D point '
    assert (len(new_point) == 2), ' Translated point is not a 2D point '
    angle = grades_to_radians(deg)
    sRT = np.array([[np.cos(angle),-np.sin(angle),new_point[0]],[np.sin(angle),np.cos(angle),new_point[1]]])
    sRT *= scale_factor
    point = euclidean2D_to_homogeneus(point)
    return sRT@point

In [21]:
rot_tra_scale(point, translated_point, deg_to_rotate, scale_factor)

array([-8., 12.])